feat: Factory Transfer Voucher
EuclidProtocol/euclid-core-contracts pull request #67
Opened 2024-09-20 14:21 UTC by joemonem

# Pull Request

## Description
This adds the ability to transfer voucher from user to another. 

## Type of Change

- [ ] Bug fix
- [x ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Refactor/Chore

## Related Issue

[Link to related issue, if applicable]

## Testing

Steps to test:

1. [Step 1]
2. [Step 2]
3. [Step 3]

## Checklist

- [x ] Self-review completed
- [ ] Tests added/updated (if applicable)
- [ ] Documentation updated (if applicable)

## Screenshots (if applicable)

[Add screenshots here]

## Additional Notes

[Any additional information or context]

2024-10-03 12:21 UTC, SlayerAnsh requested changes

2024-10-03 12:21 UTC, SlayerAnsh commented on packages/euclid/src/msgs/factory/msg.rs
> +        recipient_address: CrossChainUserWithLimit,
CrossChainUser, limit is not needed for transfering Virtual Balance

2024-10-03 12:21 UTC, SlayerAnsh commented on packages/euclid/src/msgs/router.rs
> +    TransferVoucher {
We should name it same as factory message, TransferVirtualBalance

2024-10-03 12:21 UTC, SlayerAnsh commented on contracts/hub/router/src/contract.rs
> +                ExecuteMsg::TransferVirtualBalanceInternal {
This is probably not needed. A reusable function that can be used above in TransferVoucher and Ibc receive will be sufficient.

2024-10-03 12:21 UTC, SlayerAnsh commented on contracts/hub/router/src/contract.rs
> +                    cross_chain_addresses,
CrossChainAddresses not needed, all funds should be transfered to recipient

2024-10-14 07:57 UTC, SlayerAnsh requested changes

2024-10-14 07:57 UTC, SlayerAnsh commented on packages/euclid/src/msgs/router.rs
> +        amount: Option<Uint128>,
Amount should be required

2024-10-14 07:57 UTC, SlayerAnsh commented on contracts/hub/router/src/execute.rs
> +        msg: to_json_binary(&ExecuteMsg::TransferVirtualBalance {
This is calling same function, infinite callback. We want to call virtual balance Transfer Method with sender being info.sender and chain uid is VSL chain uid

2024-10-14 07:57 UTC, SlayerAnsh commented on contracts/hub/router/src/ibc/receive.rs
> +            ibc_execute_transfer_virtual_balance(deps.branch(), env, msg)
Add a check for sender chain uid and chain uid for secure msgs

2024-10-14 07:57 UTC, SlayerAnsh commented on packages/euclid/src/virtual_balance.rs
> +pub fn transfer_virtual_balance(
IMO this should be part of contract crate. Also looks very simple so maybe we don't need this function, instead directly use transfer msg? What do you think?

2024-10-14 07:57 UTC, SlayerAnsh commented on contracts/hub/router/src/execute.rs
> +pub fn execute_transfer_voucher_internal(
Seems like we can remove this msg from router. If someone wants to transfer vcoin from vsl, they can directly call virtual_balance transfer method.

2024-10-14 08:24 UTC, joemonem commented on packages/euclid/src/virtual_balance.rs
> +pub fn transfer_virtual_balance(
Agreed

2024-10-14 10:20 UTC, SlayerAnsh commented on contracts/liquidity/factory/src/execute.rs
> +            TxType::WithdrawVirtualBalance,
Typo - Wrong tx event attached here

2024-10-14 10:20 UTC, SlayerAnsh approved these changes

2024-10-14 11:51 UTC, merged