feat: Create Pool With Liquidity
EuclidProtocol/euclid-core-contracts pull request #70
Opened 2024-10-16 13:41 UTC by joemonem

# Pull Request

## Description
Allows to create a pool with liquidity

## Type of Change

- [ ] Bug fix
- [ x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Refactor/Chore

## Related Issue

[Link to related issue, if applicable]

## Testing

Steps to test:
No test yet
## Checklist

- [ ] Self-review completed
- [ ] Tests added/updated (if applicable)
- [ ] Documentation updated (if applicable)

## Screenshots (if applicable)

[Add screenshots here]

## Additional Notes
Still a work in progress

2024-11-06 17:15 UTC, SlayerAnsh requested changes

2024-11-06 17:15 UTC, SlayerAnsh commented on contracts/hub/router/src/ibc/receive.rs
> +                        address: virtual_balance_address.clone(),
Virtual balance will be minted against user similar to add liquidity

2024-11-06 17:15 UTC, SlayerAnsh commented on contracts/hub/router/src/reply.rs
> +            let pool_creation_response = from_json::<PoolCreationWithFundsResponse>(
This will always fail for register pool without funds now. We can update register pool method to only register on existing VLP so it will never instantiate new VLP

2024-11-06 17:15 UTC, SlayerAnsh commented on contracts/hub/vlp/src/execute.rs
> +    // Add liquidity part //
This can use add liqudity fn because it has checks for voucher funds being sent to vlp and also helps keep computation logic in one place so its easy to update in future.

2024-11-06 17:15 UTC, SlayerAnsh commented on contracts/liquidity/factory/src/ibc/ack_and_timeout.rs
> +                        PENDING_DEPOSIT_TOKEN.save(deps.storage, token.clone().token, &token)?;
Should we update our escrow contract instatiate msg to receive funds during instantiate? Note - If we use this approach, it should be able to use both native and cw20 funds

2024-11-06 17:16 UTC, SlayerAnsh requested changes
Changes requested for core logic. Review for testing is in progress.

2024-11-07 08:10 UTC, joemonem commented on contracts/hub/router/src/ibc/receive.rs
> +                        address: virtual_balance_address.clone(),
You mean against VLP? That's how it is in `add_liquidity`:
```rust
let mint_virtual_balance_msg =
                euclid::msgs::virtual_balance::ExecuteMsg::Mint(ExecuteMint {
                    amount: token.amount,
                    balance_key: BalanceKey {
                        cross_chain_user: CrossChainUser {
                            address: vlp_address.to_string(),
                            chain_uid: ChainUid::vsl_chain_uid()?,
                        },
                        token_id: token.token.to_string(),
                    },
                });
```

2024-11-07 08:10 UTC, joemonem commented on contracts/hub/router/src/reply.rs
> +            let pool_creation_response = from_json::<PoolCreationWithFundsResponse>(
Aren't we going to delete Create Pool without funds?

2024-11-07 08:16 UTC, joemonem commented on contracts/liquidity/factory/src/ibc/ack_and_timeout.rs
> +                        PENDING_DEPOSIT_TOKEN.save(deps.storage, token.clone().token, &token)?;
I thought about this but wasn't sure how to handle cw20 funds

2024-11-07 09:44 UTC, joemonem commented on contracts/hub/vlp/src/execute.rs
> +    // Add liquidity part //
It now calls `add_liquidity` and modified that function to handle the res in case it was called by create pool with funds

2024-11-08 10:30 UTC, SlayerAnsh commented on contracts/hub/router/src/ibc/receive.rs
> +                        address: virtual_balance_address.clone(),
Yes

2024-11-08 10:32 UTC, SlayerAnsh commented on contracts/hub/router/src/reply.rs
> +            let pool_creation_response = from_json::<PoolCreationWithFundsResponse>(
Yes, can we remove it to verify complete ibc cycle?

2024-11-08 10:34 UTC, SlayerAnsh commented on contracts/liquidity/factory/src/ibc/ack_and_timeout.rs
> +                        PENDING_DEPOSIT_TOKEN.save(deps.storage, token.clone().token, &token)?;
We can try Instantiate2, let discuss this and implement it in another PR

2024-11-13 04:02 UTC, SlayerAnsh approved these changes
LGTM!

### Future Updates
- Remove Request Pool With funds code

2024-11-13 04:13 UTC, merged