feat: Cross Chain Limits
EuclidProtocol/euclid-core-contracts pull request #71
Opened 2024-11-04 08:38 UTC by joemonem

# Pull Request

## Description
Created a `Limit` enum that contains Less than or equal, equal, and greater or equal. 
Adjusted Reply flow (will remove if unnecessary)

## Type of Change

- [ ] Bug fix
- [x ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Refactor/Chore

## Related Issue
https://app.clickup.com/t/86eqm5c36

## Testing

No tests were created. 

## Checklist

- [ x] Self-review completed
- [ ] Tests added/updated (if applicable)
- [ ] Documentation updated (if applicable)

## Screenshots (if applicable)
N/A

## Additional Notes
N/A

2024-12-02 10:48 UTC, SlayerAnsh requested changes

2024-12-02 10:48 UTC, SlayerAnsh commented on contracts/hub/router/src/reply.rs
> +pub fn on_release_escrow_reply(
This can be removed because then we would need to cover cases for return type. If its swap then swap response, if its remove liquidity or withdraw message then it will be different ack type

2024-12-02 10:48 UTC, SlayerAnsh commented on contracts/hub/router/src/reply.rs
> +                        preferred_denom: None,
Should be fine as `None` for remove liquidity, as the message can become too complex.

2024-12-02 10:48 UTC, SlayerAnsh commented on contracts/hub/router/src/reply.rs
> +                preferred_denom: None,
This should be set as preferred denom type provided during inital message as its needed for the forwarding

2024-12-02 10:48 UTC, SlayerAnsh commented on contracts/hub/router/src/execute.rs
> +    preferred_denom: Option<TokenType>,
We can add a check for correct denom using `TOKEN_DENOM` state.

2024-12-02 10:48 UTC, SlayerAnsh commented on contracts/hub/vlp/src/execute.rs
> +    _called_by_register_pool_with_funds: bool,
We can remove this

2024-12-02 10:48 UTC, SlayerAnsh commented on contracts/liquidity/escrow/src/execute.rs
> +    if let Some(forwarding_message) = forwarding_message {
Forwarding message will either send msg with funds or a cw20 send msg depending on the fund type. Goal is to send the funds as msg to recipient if forwarding msg is provided else send the funds as normal funds (like how its currently sending the msgs).

2024-12-02 10:48 UTC, SlayerAnsh commented on contracts/liquidity/escrow/src/execute.rs
> +        response = response.add_message(msg);
Forwarding message will also need a reply id which if the message fails, it will not revert the full tx instead send funds to refund address. If refund address is not provided then revert the tx by failing release completely (which should already be handled in router to mint vouchers again)

2024-12-02 13:57 UTC, joemonem commented on contracts/liquidity/escrow/src/execute.rs
> +        response = response.add_message(msg);
Should the refund address be a separate optional variable like `forwarding_message`?

2024-12-02 14:12 UTC, joemonem commented on contracts/liquidity/escrow/src/execute.rs
> +    if let Some(forwarding_message) = forwarding_message {
So should we match the deserialization of the CosmosMsg into 
```rust
            CosmosMsg::Bank(_) => {}
            CosmosMsg::Wasm(_) => {}
```

2024-12-02 17:33 UTC, SlayerAnsh commented on contracts/liquidity/escrow/src/execute.rs
> +    if let Some(forwarding_message) = forwarding_message {
If msg is None then use the normal send flow which we have currently, if its not None then check if asset is Native, if its native then a direct Wasm msg recipient with funds attached. If asset is cw20 then create a cw20 send msg with the amount and then send Wasm msg to cw20 contract.

2024-12-02 17:33 UTC, SlayerAnsh commented on contracts/liquidity/escrow/src/execute.rs
> +        response = response.add_message(msg);
Yes

2024-12-11 05:49 UTC, SlayerAnsh approved these changes
LGTM!

2024-12-11 05:49 UTC, merged