feat: Stable Pool
EuclidProtocol/euclid-core-contracts pull request #74
Opened 2024-11-20 08:21 UTC by joemonem

# Pull Request

## Description
Created `stable_vlp` which is basically a clone of `vlp` with the difference that its assets are always in equal amounts. 
Added `stable_vlp` code id in router's state. 
A `stable_vlp` is instantiated by the router during pool creation if the amount of asset 1 is equal to that of asset 2. 

## Type of Change

- [ ] Bug fix
- [x ] New feature
- [ x] Breaking change
- [ ] Documentation update
- [ ] Refactor/Chore

## Related Issue
Clickup [task](https://app.clickup.com/t/86eqm5c0f)

## Testing
`test_stable_pool` integration test

## Checklist

- [ ] Self-review completed
- [ ] Tests added/updated (if applicable)
- [ ] Documentation updated (if applicable)

## Screenshots (if applicable)
None

## Additional Notes
`compute_swap` is returning the result with two extra decimal places so, I'm dividing the result by 100. This is a temporary fix just to see if the flow is working as expected. 
There could be some additional checks at the end of the integration test to ensure that everything is working as expected.

2024-12-02 11:34 UTC, SlayerAnsh requested changes

2024-12-02 11:34 UTC, SlayerAnsh commented on contracts/hub/router/src/ibc/receive.rs
> +        let code_id = if pair_with_denom.token_1.amount == pair_with_denom.token_2.amount {
This should be part of msg if we want to create stable pool or normal pool.

2024-12-02 16:19 UTC, joemonem commented on contracts/hub/router/src/ibc/receive.rs
> +        let code_id = if pair_with_denom.token_1.amount == pair_with_denom.token_2.amount {
Should still put a check on the amounts being sent to see if they're compatible with the requested pool?

2025-03-06 10:55 UTC, SlayerAnsh requested changes

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/.circleci/config.yml
> +version: 2.1
This file can be removed.

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/.cargo/config.toml
> +[alias]
File can be removed

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/.editorconfig
> +root = true
File can be removed

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/router/src/tests.rs
> +            stable_vlp_code_id: 0,
This might cause errors, code id can never be zero

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/.github/workflows/Basic.yml
> +# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml
Unused file

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/.github/workflows/Release.yml
> +name: release wasm
Unused file

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/.gitpod.Dockerfile
> +### wasmd ###
Unused file

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/.gitpod.yml
> +image: cosmwasm/cw-gitpod-base:v0.16
Unused file

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/Developing.md
> +# Developing
Unused file , maybe?

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/Importing.md
> +# Importing
Unused file, maybe?

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/Publishing.md
> +# Publishing Contracts
Unused File Maybe?

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/src/bin/schema.rs
> +        query: QueryMsg,
Wrong import for QueryMessage

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/src/math.rs
> +    let xp = [
This is hardcoded as stable pool for 1:1 ratio, we need to use the pool provided exchange rate and also the value from pools

2025-03-06 10:55 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/src/tests.rs
> +}
Can we add test for compute_swap function for different amount of swap ratio

2025-03-06 11:56 UTC, SlayerAnsh requested changes

2025-03-06 11:56 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/src/math.rs
> +impl Decimal256Ext for Decimal256 {
We can move this file to euclid package as separate file as its kind of independent

2025-03-06 11:56 UTC, SlayerAnsh commented on contracts/hub/stable_vlp/src/math.rs
> +pub(crate) fn compute_swap(
Calculation is wrong for this, initial test with
```let offer_asset = Decimal256::from_integer(Uint256::from(100u128));
        let offer_pool = Decimal256::from_integer(Uint256::from(1000u128));
        let ask_pool = Decimal256::from_integer(Uint256::from(1000u128));
        let result = compute_swap(&offer_asset, &offer_pool, &ask_pool).unwrap();
        ```
        
        Gives `991` which seems wrong as its not 1:1 ratio?

2025-03-12 18:57 UTC, merged